
package brightstar;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class SparePartsSaleForm extends javax.swing.JFrame {

      Connection con=null;
      
    GridBagLayout layout = new GridBagLayout();
    
    
    UserDetails spare_part_panel;
    //SparePartsSaleDynamicPanel sparePartsDynamicPanel;
    UserHistory view_spare_partsSales_panel;
    
    
    
    public SparePartsSaleForm() {
        initComponents();
        
    
        spare_part_panel = new UserDetails();
        view_spare_partsSales_panel = new UserHistory();
      
       
        
        
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0;
        c.gridy = 0;
        
        
        DynamicPanel.add(spare_part_panel, c);
        
       
        
        DynamicPanel.add(view_spare_partsSales_panel, c);
        
        
        
        
        spare_part_panel.setVisible(false);
        view_spare_partsSales_panel.setVisible(false);
        //sparePartsDynamicPanel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        btn_customer = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_sparepart_sale = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_view_spareparts_sales = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1400, 700));
        setMinimumSize(new java.awt.Dimension(1400, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 0, 102));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_customer.setBackground(new java.awt.Color(0, 0, 102));
        btn_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_customerMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Menu");

        javax.swing.GroupLayout btn_customerLayout = new javax.swing.GroupLayout(btn_customer);
        btn_customer.setLayout(btn_customerLayout);
        btn_customerLayout.setHorizontalGroup(
            btn_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_customerLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel12)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        btn_customerLayout.setVerticalGroup(
            btn_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidePanel.add(btn_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, 80));

        btn_sparepart_sale.setBackground(new java.awt.Color(0, 0, 102));
        btn_sparepart_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_sparepart_saleMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Customer_20px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Details");

        javax.swing.GroupLayout btn_sparepart_saleLayout = new javax.swing.GroupLayout(btn_sparepart_sale);
        btn_sparepart_sale.setLayout(btn_sparepart_saleLayout);
        btn_sparepart_saleLayout.setHorizontalGroup(
            btn_sparepart_saleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_sparepart_saleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        btn_sparepart_saleLayout.setVerticalGroup(
            btn_sparepart_saleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_sparepart_saleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_sparepart_saleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btn_sparepart_saleLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(btn_sparepart_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 80));

        btn_view_spareparts_sales.setBackground(new java.awt.Color(0, 0, 102));
        btn_view_spareparts_sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_view_spareparts_salesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_view_spareparts_salesMousePressed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Graph_Report_20px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("History");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_view_spareparts_salesLayout = new javax.swing.GroupLayout(btn_view_spareparts_sales);
        btn_view_spareparts_sales.setLayout(btn_view_spareparts_salesLayout);
        btn_view_spareparts_salesLayout.setHorizontalGroup(
            btn_view_spareparts_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_view_spareparts_salesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel10)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        btn_view_spareparts_salesLayout.setVerticalGroup(
            btn_view_spareparts_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_view_spareparts_salesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_view_spareparts_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btn_view_spareparts_salesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(btn_view_spareparts_sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/logom.png"))); // NOI18N
        sidePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 230, 90));

        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Home_52px.png"))); // NOI18N
        sidePanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 50, 30));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 800));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btn_sparepart_saleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sparepart_saleMousePressed
        // TODO add your handling code here:
        setColor(btn_sparepart_sale);
        resetColor(btn_customer);
        resetColor(btn_view_spareparts_sales);
        //resetColor(btn_spareparts_pending);
        //resetColor(btn_sparepart_report);

        
        spare_part_panel.setVisible(true);
        //sparePartsDynamicPanel.setVisible(true);
        view_spare_partsSales_panel.setVisible(false);
        
    }//GEN-LAST:event_btn_sparepart_saleMousePressed

    private void btn_customerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMousePressed
        // TODO add your handling code here:
        setColor(btn_customer);
        resetColor(btn_sparepart_sale);
        resetColor(btn_view_spareparts_sales);
        //resetColor(btn_spareparts_pending);
       // resetColor(btn_sparepart_report);
        
        
        spare_part_panel.setVisible(false);
        //sparePartsDynamicPanel.setVisible(false);
        view_spare_partsSales_panel.setVisible(false);
        
    }//GEN-LAST:event_btn_customerMousePressed

    private void btn_view_spareparts_salesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_spareparts_salesMousePressed
        // TODO add your handling code here:
        resetColor(btn_sparepart_sale);
        resetColor(btn_customer);
        setColor(btn_view_spareparts_sales);
        //resetColor(btn_spareparts_pending);
        //resetColor(btn_sparepart_report);
        
        
        spare_part_panel.setVisible(false);
        view_spare_partsSales_panel.setVisible(true);
        //sparePartsDynamicPanel.setVisible(false);
        
    }//GEN-LAST:event_btn_view_spareparts_salesMousePressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
   
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btn_view_spareparts_salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_spareparts_salesMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btn_view_spareparts_salesMouseClicked

    
    void setColor(JPanel panel){
        panel.setBackground(new Color(0,102,204));
    }
    
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(0,51,153));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SparePartsSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SparePartsSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SparePartsSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SparePartsSaleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SparePartsSaleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel btn_customer;
    private javax.swing.JPanel btn_sparepart_sale;
    private javax.swing.JPanel btn_view_spareparts_sales;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
