/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brightstar;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JPanel;
import office_man_system.Home;

/**
 *
 * @author Admin
 */
public class Stock extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();
    
   AddSpareParts cust_panel;
   AddMparts spare_part_panel;
  
   
   MReport spare_parts_report;
   StockReport streport; 
    
    
    public Stock() {
        initComponents();
        
        cust_panel = new AddSpareParts();
        spare_part_panel = new AddMparts();
       
        spare_parts_report = new MReport();
        streport=new StockReport();
        
        
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(cust_panel, c);
        
        DynamicPanel.add(spare_part_panel, c);
        
     
        DynamicPanel.add(spare_parts_report, c);
        
        DynamicPanel.add(streport, c);
        
        cust_panel.setVisible(true);
        spare_part_panel.setVisible(false);
       
        spare_parts_report.setVisible(false);
        streport.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        btn_customer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_sparepart_sale = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_sparepart_report = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_sparepart_report1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bright Star Office Management System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1400, 700));
        setMinimumSize(new java.awt.Dimension(1400, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 51, 153));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_customer.setBackground(new java.awt.Color(0, 51, 153));
        btn_customer.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                btn_customerAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btn_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_customerMousePressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Fax_50px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Spare Parts");

        javax.swing.GroupLayout btn_customerLayout = new javax.swing.GroupLayout(btn_customer);
        btn_customer.setLayout(btn_customerLayout);
        btn_customerLayout.setHorizontalGroup(
            btn_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(246, 246, 246))
        );
        btn_customerLayout.setVerticalGroup(
            btn_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(btn_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 50));

        btn_sparepart_sale.setBackground(new java.awt.Color(0, 51, 153));
        btn_sparepart_sale.setForeground(new java.awt.Color(0, 51, 153));
        btn_sparepart_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_sparepart_saleMousePressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Computer_48px_1.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Machine Parts");

        javax.swing.GroupLayout btn_sparepart_saleLayout = new javax.swing.GroupLayout(btn_sparepart_sale);
        btn_sparepart_sale.setLayout(btn_sparepart_saleLayout);
        btn_sparepart_saleLayout.setHorizontalGroup(
            btn_sparepart_saleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_sparepart_saleLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(246, 246, 246))
        );
        btn_sparepart_saleLayout.setVerticalGroup(
            btn_sparepart_saleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(btn_sparepart_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, -1));

        btn_sparepart_report.setBackground(new java.awt.Color(0, 51, 153));
        btn_sparepart_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_sparepart_reportMousePressed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Graph_Report_Script_50px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Machine Report");

        javax.swing.GroupLayout btn_sparepart_reportLayout = new javax.swing.GroupLayout(btn_sparepart_report);
        btn_sparepart_report.setLayout(btn_sparepart_reportLayout);
        btn_sparepart_reportLayout.setHorizontalGroup(
            btn_sparepart_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_sparepart_reportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(246, 246, 246))
        );
        btn_sparepart_reportLayout.setVerticalGroup(
            btn_sparepart_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_sparepart_reportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidePanel.add(btn_sparepart_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 300, 50));

        btn_sparepart_report1.setBackground(new java.awt.Color(0, 51, 153));
        btn_sparepart_report1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_sparepart_report1FocusGained(evt);
            }
        });
        btn_sparepart_report1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_sparepart_report1MousePressed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Graph_Report_50px.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Stock Report");

        javax.swing.GroupLayout btn_sparepart_report1Layout = new javax.swing.GroupLayout(btn_sparepart_report1);
        btn_sparepart_report1.setLayout(btn_sparepart_report1Layout);
        btn_sparepart_report1Layout.setHorizontalGroup(
            btn_sparepart_report1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_sparepart_report1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(246, 246, 246))
        );
        btn_sparepart_report1Layout.setVerticalGroup(
            btn_sparepart_report1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_sparepart_report1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(btn_sparepart_report1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/Webp.net-resizeimage (1).png"))); // NOI18N
        sidePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 70));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 800));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 1200, 710));

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Stock Management System");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Product_52px.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Home_52px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brightstar/images/icons8_Go_Back_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(170, 170, 170)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1200, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btn_sparepart_saleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sparepart_saleMousePressed
        // TODO add your handling code here:
        setColor(btn_sparepart_sale);
        resetColor(btn_customer);
       
        resetColor(btn_sparepart_report);
         resetColor(btn_sparepart_report1);

        cust_panel.setVisible(false);
        spare_part_panel.setVisible(true);
       
        spare_parts_report.setVisible(false);
        streport.setVisible(false);
    }//GEN-LAST:event_btn_sparepart_saleMousePressed

    private void btn_customerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMousePressed
        // TODO add your handling code here:
        setColor(btn_customer);
        resetColor(btn_sparepart_sale);
       
        resetColor(btn_sparepart_report);
         resetColor(btn_sparepart_report1);
         
        cust_panel.setVisible(true);
        spare_part_panel.setVisible(false);
      
        spare_parts_report.setVisible(false);
         streport.setVisible(false);
    }//GEN-LAST:event_btn_customerMousePressed

    private void btn_sparepart_reportMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sparepart_reportMousePressed
        // TODO add your handling code here:
        resetColor(btn_sparepart_sale);
        resetColor(btn_customer);
        
        setColor(btn_sparepart_report);
        resetColor(btn_sparepart_report1);
        
        cust_panel.setVisible(false);
        spare_part_panel.setVisible(false);
       
        spare_parts_report.setVisible(true);
        streport.setVisible(false);
    }//GEN-LAST:event_btn_sparepart_reportMousePressed

    private void btn_sparepart_report1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sparepart_report1MousePressed
        resetColor(btn_sparepart_sale);
        resetColor(btn_customer);
       
        resetColor(btn_sparepart_report);
        setColor(btn_sparepart_report1);
        
        cust_panel.setVisible(false);
        spare_part_panel.setVisible(false);
   
       
        spare_parts_report.setVisible(false);
        streport.setVisible(true);
    }//GEN-LAST:event_btn_sparepart_report1MousePressed

    private void btn_customerAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btn_customerAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_customerAncestorMoved

    private void btn_sparepart_report1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_sparepart_report1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sparepart_report1FocusGained

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        
        Home home = new Home();
        home.setVisible(rootPaneCheckingEnabled);
        closeWindow();
    }//GEN-LAST:event_jLabel5MouseClicked

    
    public void closeWindow(){
        
        WindowEvent windowClose;
        windowClose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(0,102,204));
    }
    
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(0,51,153));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel btn_customer;
    private javax.swing.JPanel btn_sparepart_report;
    private javax.swing.JPanel btn_sparepart_report1;
    private javax.swing.JPanel btn_sparepart_sale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
