/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brightstar.frames;


import brightstar.Maintenance.GroupButtonUtils;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import brightstar.connection.DBConnection;

/**
 *
 * @author Yasith
 */
public class UpdateMaintenanceForm extends javax.swing.JFrame {
    
   
    
    /**
     * Creates new form UpdateMaintenance
     */
    public UpdateMaintenanceForm() {
        initComponents();
        
    }
    public UpdateMaintenanceForm(String one,String two,String three,String four,String five,String six,String seven,String eight){
        initComponents();
        
        JcomplainId.setText(one);
        JcustomerName.setText(two);
        Jaddress.setText(three);
        JphoneNumber.setText(four);
        Jemail.setText(five);
        Jissue.setText(six);
        //Jdate.addItem(six);
        //Jmodel.addItem(seven);
        // JpaymentMethode.setText(eight);
        //  JmachineStatus.setText(nine);
        // System.out.println(eight + nine);
        
        if(seven.equals("Toshiba")){
          JmachineBrand.setSelectedItem("Toshiba");
        
        }
        if(seven.equals("Ricoh")){
            
           JmachineBrand.setSelectedItem("Ricoh");
        }
        if(eight.equals("Black")){
            
          Jmodel.setSelectedItem("Black");
        
        }
        if(eight.equals("Colour")){
            
           Jmodel.setSelectedItem("Colour");
        }
        
       
       
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentMethode = new javax.swing.ButtonGroup();
        MaintenanceStatus = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        JcustomerName = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        JcomplainId = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Jemail = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Jaddress = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        JphoneNumber = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Jmodel = new javax.swing.JComboBox<>();
        JmachineBrand = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jiss = new javax.swing.JLabel();
        Jissue = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1200, 700));
        jPanel3.setMinimumSize(new java.awt.Dimension(1200, 700));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Customer Name");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Address");

        JcustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcustomerNameActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Machine Brand");

        JcomplainId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomplainIdActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Model");

        Jemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JemailActionPerformed(evt);
            }
        });
        Jemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JemailKeyReleased(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Email");

        Jaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JaddressActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Phone Number");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Update Maintenance Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Complaint ID");

        JphoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JphoneNumberActionPerformed(evt);
            }
        });
        JphoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JphoneNumberKeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Jmodel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Model", "Black", "Colour", " " }));

        JmachineBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Brand", "Toshiba", "Ricoh" }));
        JmachineBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmachineBrandActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));

        Jiss.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Jiss.setText("Issue");

        Jissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JissueActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(JcustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(Jaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(JcomplainId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(JphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel26)
                                        .addComponent(Jmodel, 0, 175, Short.MAX_VALUE)
                                        .addComponent(jLabel25)
                                        .addComponent(JmachineBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Jissue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Jiss)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Jemail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JcomplainId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jissue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JcustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JmachineBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JphoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JcustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcustomerNameActionPerformed

    private void JemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JemailActionPerformed

    private void JaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JaddressActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_JaddressActionPerformed
    
    //JOptionPane.showConfirmDialog(null, "Do you really want to update");
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
            String ComplainId = JcomplainId.getText();
            String CustomerName = JcustomerName.getText();
            String Address = Jaddress.getText();
            String PhoneNumber = JphoneNumber.getText();
            String Email = Jemail.getText();
            String Issue = Jissue.getText();
            String MachineBrand = JmachineBrand.getSelectedItem().toString();
            String Model = Jmodel.getSelectedItem().toString();
           // Format formatter = new SimpleDateFormat("yyyy-MM-dd");
            //String Date = formatter.format(Jdate.getDate());
            //String paymentMethode = GroupButtonUtils.getSelectedButtonText(PaymentMethode);
            //String maintenanceStatus = GroupButtonUtils.getSelectedButtonText(MaintenanceStatus);
            
            
          
            try{
            String updateMaintenanceQuery = "UPDATE machinemaintenancenew "
                    +"SET CustomerName = ?, Address = ?, PhoneNumber = ?, Email = ?,Issue = ?,MachineBrand = ?, Model = ?"
                    + "WHERE ComplainId = ?";
           
            PreparedStatement ps = DBConnection.getDBconnection().prepareStatement(updateMaintenanceQuery);
            
            //ps.setString(1, customerName);
            ps.setString(1, CustomerName);
            ps.setString(2, Address);
            ps.setString(3, PhoneNumber);
            ps.setString(4, Email);
            ps.setString(5, Issue);
            ps.setString(6, MachineBrand);
            ps.setString(7, Model);
            //ps.setShort(8, Date);
            
            ps.setString(8, ComplainId);
            ps.executeUpdate();
                        
            System.out.println(ComplainId + ","+CustomerName +  ","+Address +  ","+PhoneNumber +  ","+Email +  ","+Issue + ","+MachineBrand +  ","+Model);

            JOptionPane.showMessageDialog(null, "Maintenance Updated successfully!",
                    "Confirmation Message", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(UpdateMaintenanceForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateMaintenanceForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
          if(ComplainId.isEmpty()){
                JOptionPane.showMessageDialog(null, "Complaint Id Can Not Be EMPTY!");
                JcomplainId.setForeground(Color.RED);
            }
            if(CustomerName.isEmpty()){
                JOptionPane.showMessageDialog(null, "Customer Name Can Not Be EMPTY!");
                JcustomerName.setForeground(Color.RED);
            }
            if(Address.isEmpty()){
                JOptionPane.showMessageDialog(null, "Address Can Not Be EMPTY!");
                Jaddress.setForeground(Color.RED);
            }
            if(PhoneNumber.isEmpty()){
                JOptionPane.showMessageDialog(null, "Phone Number Can Not Be EMPTY!");
                JphoneNumber.setForeground(Color.RED);
            }
            if(Email.isEmpty()){
                JOptionPane.showMessageDialog(null, "Email Can Not Be EMPTY!");
                Jemail.setForeground(Color.RED);
            }
            if(Issue.isEmpty()){
                JOptionPane.showMessageDialog(null, "Address Can Not Be EMPTY!");
                Jissue.setForeground(Color.RED);
            }
            if(MachineBrand.isEmpty()){
                JOptionPane.showMessageDialog(null, "Machine Brand Can Not Be EMPTY!");
                JmachineBrand.setForeground(Color.RED);
            }
            if(Model.isEmpty()){
                JOptionPane.showMessageDialog(null, "Model Can Not Be EMPTY!");
                Jmodel.setForeground(Color.RED);
            }
            else{
                 JOptionPane.showMessageDialog(null, "Validation is Successfully");
            }
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        
            String ComplainId = JcomplainId.getText();
            String CustomerName = JcustomerName.getText();
            String Address = Jaddress.getText();
            String PhoneNumber = JphoneNumber.getText();
            String Email = Jemail.getText();
            String Issue = Jissue.getText();
            String MachineBrand = JmachineBrand.getSelectedItem().toString();
            String Model = Jmodel.getSelectedItem().toString();
            //String paymentMethode = GroupButtonUtils.getSelectedButtonText(PaymentMethode);
           // String maintenanceStatus = GroupButtonUtils.getSelectedButtonText(MaintenanceStatus);
          try {  
            String deleteMaintenanceQuery = "DELETE FROM machinemaintenancenew WHERE ComplainId = ?";
            
            PreparedStatement ps = DBConnection.getDBconnection().prepareStatement(deleteMaintenanceQuery);
            
            ps.setString(1, ComplainId);

            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Maintenance removed successfully!", 
                    "Confirmation Message", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateMaintenanceForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UpdateMaintenanceForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JphoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JphoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JphoneNumberActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int state = JOptionPane.showConfirmDialog(null, "Do you want to cancel?", "Alert", JOptionPane.YES_NO_OPTION);
        
        if(state == 0){
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JcomplainIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomplainIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcomplainIdActionPerformed

    private void JmachineBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmachineBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JmachineBrandActionPerformed

    private void JemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JemailKeyReleased
        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern pattern = Pattern.compile(EMAIL_PATTERN);
        Matcher matcher = pattern.matcher(Jemail.getText());

        if (!matcher.matches()) {
            jLabel3.setText("email is incorrect");
            
        } else {
            jLabel3.setText(null);
           
        }
    }//GEN-LAST:event_JemailKeyReleased

    private void JphoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JphoneNumberKeyReleased
        // TODO add your handling code here:
         Pattern pattern = Pattern.compile("^[0-9, ]+$");
        Matcher matcher = pattern.matcher(JphoneNumber.getText());

        if (!matcher.matches() || JphoneNumber.getText().length() != 10) {
            jLabel2.setText("Invalid Phone Number");
          
        } else {
            jLabel2.setText(null);
        }
           
        
    }//GEN-LAST:event_JphoneNumberKeyReleased

    private void JissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JissueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JissueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMaintenanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMaintenanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMaintenanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMaintenanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMaintenanceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jaddress;
    private javax.swing.JTextField JcomplainId;
    private javax.swing.JTextField JcustomerName;
    private javax.swing.JTextField Jemail;
    private javax.swing.JLabel Jiss;
    private javax.swing.JTextField Jissue;
    private javax.swing.JComboBox<String> JmachineBrand;
    private javax.swing.JComboBox<String> Jmodel;
    private javax.swing.JTextField JphoneNumber;
    private javax.swing.ButtonGroup MaintenanceStatus;
    private javax.swing.ButtonGroup PaymentMethode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
