/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brightstar.frames;

import brightstar.generate.GenerateMaintenanceDonePDF;
import brightstar.generate.SendMaintenanceDoneEmail;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import brightstar.connection.DBConnection;

/**
 *
 * @author Yasith
 */
public class UpdatePendingMaintenanceForm extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePendingMaintenanceForm
     */
    public UpdatePendingMaintenanceForm() {
        initComponents();
    }

    public UpdatePendingMaintenanceForm(String one, String two) {
            initComponents();
            
            JcomplainId.setText(one);
            
            if(two.equals("Done")){
    
                Jdone.setSelected(true);
            }
                if(two.equals("Pending")){
    
                 Jpending.setSelected(true);
             }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentMethod = new javax.swing.ButtonGroup();
        MaintenanceStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        JcomplainId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JmaintenanceStatus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        Jdone = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Jpending = new javax.swing.JRadioButton();
        JcompletedDate = new com.toedter.calendar.JDateChooser();
        JmaintenanceStatus1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Update And Send Email");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JcomplainId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomplainIdActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Complain Id");

        JmaintenanceStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JmaintenanceStatus.setText("Maintenance Status");

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(" Update Pending Payments");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MaintenanceStatus.add(Jdone);
        Jdone.setText("Done");
        Jdone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JdoneActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("If the Maintenance Is Successfull Done  Chanege the Maintenance Status As Done");

        MaintenanceStatus.add(Jpending);
        Jpending.setText("Pending");
        Jpending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpendingActionPerformed(evt);
            }
        });

        JmaintenanceStatus1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        JmaintenanceStatus1.setText("Completed Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JmaintenanceStatus)
                            .addComponent(jLabel3)
                            .addComponent(JmaintenanceStatus1))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JcomplainId, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Jdone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Jpending))
                            .addComponent(JcompletedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JcomplainId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jdone)
                    .addComponent(Jpending)
                    .addComponent(JmaintenanceStatus))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JcompletedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JmaintenanceStatus1))
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JcomplainIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomplainIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcomplainIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
       String complainId = JcomplainId.getText();
       boolean Done = Jdone.isSelected();
       boolean Pending = Jpending.isSelected();
       Format formatter = new SimpleDateFormat("yyyy-MM-dd");
       String CompletedDate = formatter.format(JcompletedDate.getDate());
       String MaintenanceStatus = "null";
            
       if(Done == true){
                
                MaintenanceStatus = "Done";
               
                
       }
       else if(Pending = true){
    
             MaintenanceStatus = "Pending ";
        }
       
       
       try{
       String updatePendingMaintenanceQuery = "UPDATE machinemaintenancenew "
                    +"SET maintenanceStatus =  ?, completeDate = ?"
                    + "WHERE complainId = ?";
       
       PreparedStatement ps = DBConnection.getDBconnection().prepareStatement(updatePendingMaintenanceQuery);
       
        
        ps.setString(1, MaintenanceStatus); 
        ps.setString(2, CompletedDate);
        ps.setString(3, complainId);
        
        ps.executeUpdate();
        
        GenerateMaintenanceDonePDF.createPDF(complainId, MaintenanceStatus, CompletedDate);
        SendMaintenanceDoneEmail.create_sendEmail(complainId, "yasithnawanjana996@gmail.com");
        
        JOptionPane.showMessageDialog(null, "Pending MaintenanceStatus Updated successfully!",
        "Confirmation Message", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdatePendingMaintenanceForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UpdatePendingMaintenanceForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JdoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JdoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JdoneActionPerformed

    private void JpendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpendingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePendingMaintenanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePendingMaintenanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePendingMaintenanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePendingMaintenanceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePendingMaintenanceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JcomplainId;
    private com.toedter.calendar.JDateChooser JcompletedDate;
    private javax.swing.JRadioButton Jdone;
    private javax.swing.JLabel JmaintenanceStatus;
    private javax.swing.JLabel JmaintenanceStatus1;
    private javax.swing.JRadioButton Jpending;
    private javax.swing.ButtonGroup MaintenanceStatus;
    private javax.swing.ButtonGroup PaymentMethod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
