/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brightstar.panels;

import brightstar.connection.DBConnection;
import brightstar.frames.EditCustomerForm;
import brightstar.frames.AddCustomerForm;
import brightstar.model.SparepartBuyer;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Admin
 */
public class CustomersPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomersPanel
     */
    public CustomersPanel() {
        initComponents();

        //edit table header
        JTableHeader tHeader = display_buyers.getTableHeader();
        tHeader.setFont(new Font("Segoe UI", Font.BOLD, 20));

        viewBuyerTable();
    }

    public ArrayList<SparepartBuyer> getAllSparepartBuyers() {

        ArrayList<SparepartBuyer> buyerList = new ArrayList<>();

        String viewAllBuyersQuery = "SELECT * FROM sparepart_buyer";

        try {
            PreparedStatement ps = DBConnection.getDBconnection().prepareStatement(viewAllBuyersQuery);

            ResultSet resultSet = ps.executeQuery();

            while (resultSet.next()) {
                SparepartBuyer buyer = new SparepartBuyer();
                buyer.setBuyerID(resultSet.getString(1));
                buyer.setNIC(resultSet.getString(2));
                buyer.setName(resultSet.getString(3));
                buyer.setPhone(resultSet.getString(4));
                buyer.setAddress(resultSet.getString(5));
                buyer.setCompany(resultSet.getString(6));
                buyer.setEmail(resultSet.getString(7));
                buyerList.add(buyer);
            }

            ps.close();
            resultSet.close();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomersPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex,
                    "Alert!", JOptionPane.PLAIN_MESSAGE);

        } catch (SQLException ex) {
            Logger.getLogger(CustomersPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex,
                    "Alert", JOptionPane.PLAIN_MESSAGE);

        }

        return buyerList;

    }

    public void viewBuyerTable() {

        ArrayList<SparepartBuyer> buyerList = getAllSparepartBuyers();
        DefaultTableModel model = (DefaultTableModel) display_buyers.getModel();
        String[] row = new String[7];

        for (int i = 0; i < buyerList.size(); i++) {
            row[0] = buyerList.get(i).getBuyerID();
            row[1] = buyerList.get(i).getNIC();
            row[2] = buyerList.get(i).getName();
            row[3] = buyerList.get(i).getPhone();
            row[4] = buyerList.get(i).getAddress();
            row[5] = buyerList.get(i).getCompany();
            row[6] = buyerList.get(i).getEmail();

            model.addRow(row);
        }

    }

    public void clearTable() {

        DefaultTableModel dm = (DefaultTableModel) display_buyers.getModel();
        dm.getDataVector().removeAllElements();
        revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        display_buyers = new javax.swing.JTable();
        btn_newCustomer = new javax.swing.JButton();
        sparepartsdetails = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        display_buyers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        display_buyers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "NIC", "Name", "Phone", "Address", "Company", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        display_buyers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        display_buyers.setRowHeight(30);
        display_buyers.setSelectionBackground(new java.awt.Color(0, 51, 255));
        display_buyers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_buyersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(display_buyers);
        if (display_buyers.getColumnModel().getColumnCount() > 0) {
            display_buyers.getColumnModel().getColumn(1).setResizable(false);
            display_buyers.getColumnModel().getColumn(2).setResizable(false);
            display_buyers.getColumnModel().getColumn(3).setResizable(false);
            display_buyers.getColumnModel().getColumn(4).setResizable(false);
            display_buyers.getColumnModel().getColumn(5).setResizable(false);
            display_buyers.getColumnModel().getColumn(6).setResizable(false);
        }

        btn_newCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_newCustomer.setText("New Customer");
        btn_newCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newCustomerActionPerformed(evt);
            }
        });

        sparepartsdetails.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sparepartsdetails.setText("Spare Parts Buyer Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sparepartsdetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_newCustomer)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_newCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sparepartsdetails))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newCustomerActionPerformed
        // TODO add your handling code here:

        AddCustomerForm addCustomer = new AddCustomerForm();
        addCustomer.setVisible(true);
    }//GEN-LAST:event_btn_newCustomerActionPerformed

    private void display_buyersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_buyersMouseClicked
        // TODO add your handling code here:
        int selectedRow = display_buyers.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) display_buyers.getModel();

        String buyerID = model.getValueAt(selectedRow, 0).toString();
        String nic = model.getValueAt(selectedRow, 1).toString();
        String name = model.getValueAt(selectedRow, 2).toString();
        String phone = model.getValueAt(selectedRow, 3).toString();
        String address = model.getValueAt(selectedRow, 4).toString();
        String company = model.getValueAt(selectedRow, 5).toString();
        String email = model.getValueAt(selectedRow, 6).toString();

        EditCustomerForm editCustomer = new EditCustomerForm(buyerID, nic, name, phone, address, company, email);
        editCustomer.setVisible(true);

    }//GEN-LAST:event_display_buyersMouseClicked

    public void refreshBuyerTable() {
        clearTable();
        viewBuyerTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_newCustomer;
    private javax.swing.JTable display_buyers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sparepartsdetails;
    // End of variables declaration//GEN-END:variables
}
