/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brightstar.panels;


import brightstar.Maintenance.Maintenance;
import brightstar.frames.AddMaintenanceForm;
import brightstar.frames.RemoveMaintenanceForm;
import brightstar.frames.UpdateMaintenanceForm;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import brightstar.connection.DBConnection;

/**
 *
 * @author Admin
 */
public class MaintenancePanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomersPanel
     */
    public MaintenancePanel() {
        initComponents();
        
        
        
       JTableHeader tHeader = jTable2.getTableHeader();
        
       tHeader.setFont(new Font("Segoe UI", Font.BOLD, 17));
        
       viewMaintenanceTable();
    
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel30.setText("View Maintenance Details");

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Complain Id", "Customer Name", "Address", "Phone Number", "Email", "Issue", "Machine Brand", "Model", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("Add Maintenance");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Click row to update maintenance details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(448, 448, 448)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clearTable();
        viewMaintenanceTable();
    }//GEN-LAST:event_jButton3ActionPerformed
  
    
    public ArrayList<Maintenance> getAllMaintenance(){
        
        ArrayList<Maintenance> mainList = new ArrayList<>();
        String viewAllMaintenanceQueary  = "SELECT * FROM machinemaintenancenew";
        
        try {
            PreparedStatement ps = DBConnection.getDBconnection().prepareStatement(viewAllMaintenanceQueary );
            
            ResultSet resultSet = ps.executeQuery();
            
            while(resultSet.next()){
               
                Maintenance maintenance = new Maintenance();
            
                maintenance.setComplainId(resultSet.getString(1));
                maintenance.setCustomerName(resultSet.getString(2));
                maintenance.setAddress(resultSet.getString(3));
                maintenance.setPhoneNumber(resultSet.getString(4));
                maintenance.setEmail(resultSet.getString(5));
                maintenance.setIssue(resultSet.getString(6));
                maintenance.setMachineBrand(resultSet.getString(7));
                maintenance.setModel(resultSet.getString(8));
                maintenance.setDate(resultSet.getString(11));
                //maintenance.setDate(resultSet.getString(9));
                //maintenance.setPaymentMethode(resultSet.getString(8));
                //maintenance.setMaintenanceStatus(resultSet.getString(9));
                
                
                mainList.add(maintenance);
                
                
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MaintenancePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MaintenancePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        return mainList;
            
    }
    public void viewMaintenanceTable(){
    
        ArrayList<Maintenance> mainList = getAllMaintenance();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        String[] row = new String[10];
            
        for(int i = 0; i < mainList.size(); i++){
            row[0] = mainList.get(i).getComplainId();
            row[1] = mainList.get(i).getCustomerName();
            row[2] = mainList.get(i).getAddress();
            row[3] = mainList.get(i).getPhoneNumber();
            row[4] = mainList.get(i).getEmail();
            row[5] = mainList.get(i).getIssue();
            row[6] = mainList.get(i).getMachineBrand();
            row[7] = mainList.get(i).getModel();
            row[8] = mainList.get(i).getDate();
            //row[8] = mainList.get(i).getDate();
            //row[8] = mainList.get(i).getMaintenanceStatus();
            
            model.addRow(row);
            
        }
        
    }
    public void clearTable(){
        
    DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
    dm.getDataVector().removeAllElements();
    revalidate();
}
    
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        DefaultTableModel mode = (DefaultTableModel)jTable2.getModel();
        
        String one = mode.getValueAt(row, 0).toString();
        String two = mode.getValueAt(row, 1).toString();
        String three = mode.getValueAt(row, 2).toString();
        String four = mode.getValueAt(row, 3).toString();
        String five = mode.getValueAt(row, 4).toString();
        String six = mode.getValueAt(row, 5).toString();
        String seven = mode.getValueAt(row, 6).toString();
        String eight = mode.getValueAt(row, 7).toString();
        //String nine = mode.getValueAt(row, 8).toString();
        
        UpdateMaintenanceForm frame = new UpdateMaintenanceForm(one,two,three,four,five,six,seven,eight);
        frame.setVisible(true);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        AddMaintenanceForm addMaintenance = new AddMaintenanceForm();
        addMaintenance.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
