/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package office_man_system;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import office_man_system.GenerateRentInvoicePDF;
import office_man_system.SendRentInvoiceEmail;

/**
 *
 * @author Pasindu Senarathne
 */
public class CheckOut extends javax.swing.JFrame {

   GridBagLayout layout = new GridBagLayout();
   
   Preview_Reg regView;
   
    public CheckOut() {
        initComponents();
        /*
        regView = new Preview_Reg();
        
        dynamic_panel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0;
        c.gridy = 0;
        
        dynamic_panel.add(regView, c);
        
        regView.setVisible(true);
        */
        
    }
    
     public CheckOut(String nameCus,String nicCus,String phoneNumber,String addressCus ,String depositAmount ,String chequeNum,String issuedDate,String bankName,String mail,String state) {
         
        initComponents();
        
        address.setText(addressCus);
        bank.setText(bankName);
        cheque.setText(chequeNum);
        customerName.setText(nameCus);
        date.setText(issuedDate);
        diposit.setText(depositAmount);
        stateReg.setText(state);
        nic.setText(nicCus);
        phone.setText(phoneNumber);
        email.setText(mail);
         
    }
     
    public void addMachine(String machineBrand,String type,String serial,String copyCount,String status,String discription){
        
        Object[] row = { machineBrand, type, serial, copyCount, status,discription};
        
        DefaultTableModel model = (DefaultTableModel) preview1.getModel();
        
        model.addRow(row);

    }
    
    public ArrayList<RentedMachines> getItems(){
    
        ArrayList<RentedMachines> itemList = new ArrayList<>();
        DefaultTableModel invoiceModel = (DefaultTableModel) preview1.getModel();
        
            for(int i = 0; i < invoiceModel.getRowCount(); i++){
                RentedMachines item = new RentedMachines();
                item.setBrand((String) invoiceModel.getValueAt(i, 0));
                item.setType((String) invoiceModel.getValueAt(i, 1));
                item.setSerial((String) invoiceModel.getValueAt(i, 2));
                item.setCopyCount((String) invoiceModel.getValueAt(i, 3));
                item.setStatus((String) invoiceModel.getValueAt(i, 4));
                item.setDiscription((String) invoiceModel.getValueAt(i, 5));
            
                itemList.add(item);
            }
    
        return itemList;
    }
      
    public Connection getConnection(){
        
        Connection con;
        try {
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/office_management_system?autoReconnect=true&useSSL=false","root","root");
            return con;
            
        } catch (Exception e) {
            
            e.printStackTrace();
            return null;
        }
      
    }

     public void close(){
        
        WindowEvent windowClose;
        windowClose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back_btn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        preview1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        print_btn = new javax.swing.JButton();
        customerName = new javax.swing.JLabel();
        diposit = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        cheque = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        stateText = new javax.swing.JLabel();
        stateReg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CheckOut");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Cash_Register_52px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CheckOut");

        back_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Back_Arrow_40px.png"))); // NOI18N
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                back_btnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(back_btn)
                .addGap(385, 385, 385)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(back_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1500, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 700));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 700));

        preview1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        preview1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Machine Brand", "Type", "Serial Number", "Copy Count", "Status", "Discription"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        preview1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(preview1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Date :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("NIC Number :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Customer :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Phone Number :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Deposit Amount :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Address :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Cheque Number :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Bank :");

        print_btn.setBackground(new java.awt.Color(255, 255, 255));
        print_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        print_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Print_35px.png"))); // NOI18N
        print_btn.setText("Submit And Print Invoice");
        print_btn.setToolTipText("");
        print_btn.setIconTextGap(10);
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });

        customerName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerName.setText("jLabel12");
        customerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerNameMouseClicked(evt);
            }
        });

        diposit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diposit.setText("jLabel12");
        diposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dipositMouseClicked(evt);
            }
        });

        phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phone.setText("jLabel12");
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });

        address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        address.setText("jLabel12");
        address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressMouseClicked(evt);
            }
        });

        nic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nic.setText("jLabel12");
        nic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nicMouseClicked(evt);
            }
        });

        cheque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cheque.setText("jLabel12");
        cheque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chequeMouseClicked(evt);
            }
        });

        bank.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bank.setText("jLabel12");
        bank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bankMouseClicked(evt);
            }
        });

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setText("jLabel12");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Remove_Tag_15px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Edit_Row_15px.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Email Address");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("jLabel12");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
        });

        stateText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stateText.setText("Register State :");

        stateReg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        stateReg.setText("jLabel12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stateReg, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(277, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bank, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(57, 57, 57)
                                        .addComponent(cheque, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(58, 58, 58)
                                        .addComponent(diposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(242, 242, 242))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateReg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(customerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nic)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cheque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(bank))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(email))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(33, 33, 33)
                .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMousePressed
        
        close(); 
    }//GEN-LAST:event_back_btnMousePressed

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed
       
        String nicNum = nic.getText();
        String name = customerName.getText();
        String addr = address.getText();
        String pNum = phone.getText();
        String depositA = diposit.getText();
        String type;
        String bankN = bank.getText();
        String chq = cheque.getText();
        String dateR = date.getText();
        String emailA = email.getText();
        String state = stateReg.getText();
        
        if(bankN == "No"){
            
            type = "Cash Payment";
        }
        else{
            
            type = "Cheque Payment";
        }
        
        if(state.equals("Unregistered")){
            
        String addQuery = "INSERT INTO rented_customers VALUES(?, ?, ?, ?, ?, ?, ?, ?,?)";
        
         PreparedStatement ps;
       try {
           ps = getConnection().prepareStatement(addQuery);
           
           ps.setString(1, nicNum);
           ps.setString(2, name);
           ps.setString(3, addr);
           ps.setString(4, pNum);
           ps.setString(5, emailA);
           ps.setString(6, depositA);
           ps.setString(7, type);
           ps.setString(8, bankN);
           ps.setString(9, chq);
         
           
           ps.executeUpdate();
           
       } catch (SQLException ex) {
           Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
       }
        } 
        
        if(state.equals("Registered")){
            
            try{
            String query = "UPDATE rented_customers "
                    + "SET customerName = '"+name+"', address = '"+addr+"', phone = '"+pNum+"', depositAmount = '"+depositA+"', bank = '"+bankN+"',chequeNum ='"+chq+"', paidType ='"+type+"',email ='"+emailA+"'"
                    + "WHERE nic = '"+nicNum+"'";
        
            PreparedStatement ps = getConnection().prepareStatement(query);
            
            ps.executeUpdate();
            
        } catch (SQLException ex) {
            
            Logger.getLogger(Update_Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        }
             
             int rows=preview1.getRowCount();

            for(int row = 0; row<rows; row++)
            {
                String nameMac = (String)preview1.getValueAt(row, 0);
                String typeOfMachine = (String)preview1.getValueAt(row, 1);
                String serialNumber = (String)preview1.getValueAt(row, 2);
                String copycount = (String)preview1.getValueAt(row, 3);
                String statusOfMachine = (String)preview1.getValueAt(row, 4);
                String machDis = (String)preview1.getValueAt(row, 5);
               
                
                String addQuery1 = "INSERT INTO rented_machine_records VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
        
                PreparedStatement ps1;
                
                try {
                        ps1 = getConnection().prepareStatement(addQuery1);

                        ps1.setString(1, nicNum);
                        ps1.setString(2, nameMac);
                        ps1.setString(3, typeOfMachine);
                        ps1.setString(4, serialNumber);
                        ps1.setString(5, copycount);
                        ps1.setString(6, statusOfMachine);
                        ps1.setString(7, machDis);
                        ps1.setString(8, dateR);
                        
                        ps1.executeUpdate();
           
                } catch (SQLException ex) {
                    Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
                
         String query1 = "DELETE FROM available_machines WHERE machineSerial= '"+serialNumber+"'";
         
        try {
            
            PreparedStatement ps2 = getConnection().prepareStatement(query1);
            ps2.executeUpdate();
             
        } catch (SQLException ex) {
            Logger.getLogger(Custome_View.class.getName()).log(Level.SEVERE, null, ex);
        }
            }  
            
            GenerateRentInvoicePDF.createPDF(name, nicNum, dateR, addr, bankN,chq, pNum, depositA, emailA,getItems());
            SendRentInvoiceEmail.create_sendEmail(nicNum, dateR, emailA);
            
            JOptionPane.showMessageDialog(null, "Registration Sucessful", "Informer", 1);
            close();
    }//GEN-LAST:event_print_btnActionPerformed

    private void customerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerNameMouseClicked
       
        String val = JOptionPane.showInputDialog(null, "Enter New Value Here", "Edit Text", 1);
        customerName.setText(val);
    }//GEN-LAST:event_customerNameMouseClicked

    private void nicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nicMouseClicked
        
         String val = JOptionPane.showInputDialog(null, "Enter New Value Here", "Edit Text", 1);
        nic.setText(val);
    }//GEN-LAST:event_nicMouseClicked

    private void addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressMouseClicked
        
       String val = JOptionPane.showInputDialog(null, "Enter New Value Here", "Edit Text", 1);
       address.setText(val);
    }//GEN-LAST:event_addressMouseClicked

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        
        String val = JOptionPane.showInputDialog(null, "Enter New Value Here", "Edit Text", 1);
        phone.setText(val);
    }//GEN-LAST:event_phoneMouseClicked

    private void chequeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chequeMouseClicked
       
        String val = JOptionPane.showInputDialog(null, "Enter New Value Here", "Edit Text", 1);
        cheque.setText(val);
    }//GEN-LAST:event_chequeMouseClicked

    private void bankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankMouseClicked
       
        String val = JOptionPane.showInputDialog(null, "Enter New Value Here", "Edit Text", 1);
        bank.setText(val);
    }//GEN-LAST:event_bankMouseClicked

    private void dipositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dipositMouseClicked
       
        String val = JOptionPane.showInputDialog(null, "Enter New Value Here", "Edit Text", 1);
        diposit.setText(val);
    }//GEN-LAST:event_dipositMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DefaultTableModel model = (DefaultTableModel) preview1.getModel();

        try {

            int index = preview1.getSelectedRow();
            model.removeRow(index);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultTableModel model = (DefaultTableModel) preview1.getModel();

        int selectedRowIndex = preview1.getSelectedRow();
        int selectedColIndex = preview1.getSelectedColumn();

        String val = JOptionPane.showInputDialog("Enter Here New Value");

        model.setValueAt(val, selectedRowIndex, selectedColIndex);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        
        String val = JOptionPane.showInputDialog(null, "Enter New Value Here", "Edit Text", 1);
        email.setText(val);
    }//GEN-LAST:event_emailMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel back_btn;
    private javax.swing.JLabel bank;
    private javax.swing.JLabel cheque;
    public javax.swing.JLabel customerName;
    private javax.swing.JLabel date;
    private javax.swing.JLabel diposit;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nic;
    private javax.swing.JLabel phone;
    public javax.swing.JTable preview1;
    private javax.swing.JButton print_btn;
    private javax.swing.JLabel stateReg;
    private javax.swing.JLabel stateText;
    // End of variables declaration//GEN-END:variables
}
