/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package office_man_system;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pasindu Senarathne
 */
public class Machine_Add extends javax.swing.JFrame {

    /**
     * Creates new form Machine_Add
     */
    public Machine_Add() {
        initComponents();
    }
    
    public Machine_Add(String brand,String type,String count,String serial,String dis,String status) {
        
        initComponents();
        
       if(brand.equals("Thoshiba")){
            
            brand_name1.setSelectedItem(brand);
        }
        if(brand.equals("Ricoh")){
            
            brand_name1.setSelectedItem(brand);
        }
        
        if(type.equals("Color")){
            
            macine_type1.setSelectedItem("Color");
        }
        if(brand.equals("Black")){
            
            macine_type1.setSelectedItem("Black");
        }
        
        count_copy1.setText(count);
        m_serial1.setText(serial);
        
        if(status.equals("Brand New")){
            
            new_m1.setSelected(true);
        }
        if(status.equals("Good Condition")){
            
            good_m1.setSelected(true);
        }
        if(status.equals("External Damages")){
            
            damage_m1.setSelected(true);
        }
        discription1.setText(dis);
    }
    
    public Connection getConnection(){
        
        Connection con;
        try {
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/office_management_system?autoReconnect=true&useSSL=false","root","root");
            return con;
            
        } catch (Exception e) {
            
            e.printStackTrace();
            return null;
        }
      
    }

     public void close(){
        
        WindowEvent windowClose;
        windowClose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
    }
     
         public boolean validateLetter(String string){
	        
	        int val;
	        boolean ret = true;
	        
	        for(int i = 0; i < string.length(); i++){
	            
	            val = (int)string.charAt(i);
	            
	            if(!(((val >=65) && (val <= 90)) || ((val >= 97) && (val <= 122)) || val == 32)){
	                
	                ret = false;
	            }
	            
	        }
	        
	        return ret;
    }
    
   
    
    public boolean validateSerialNumber(String string){
        
        if(string.length() == 10){
            
            return true;
        }
        else{
            
            return false;
        }
    }
    
    public boolean validateNumbers(String string){
	        
	        int val;
	        boolean ret = true;
	        
	        for(int i = 0; i < string.length(); i++){
	            
	            val = (int)string.charAt(i);
	            
	            if(!((val <= 57) && (val >= 48 ))){
	                
	                ret = false;
	            }
	            
	        }
	        
	        return ret;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        macine_type = new javax.swing.JComboBox<>();
        brand_name = new javax.swing.JComboBox<>();
        count_copy = new javax.swing.JTextField();
        copy_txt = new javax.swing.JLabel();
        serial_txt = new javax.swing.JLabel();
        m_serial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        new_m = new javax.swing.JRadioButton();
        good_m = new javax.swing.JRadioButton();
        damage_m = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        discription = new javax.swing.JTextArea();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        macine_type1 = new javax.swing.JComboBox<>();
        brand_name1 = new javax.swing.JComboBox<>();
        count_copy1 = new javax.swing.JTextField();
        copy_txt1 = new javax.swing.JLabel();
        serial_txt1 = new javax.swing.JLabel();
        m_serial1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        new_m1 = new javax.swing.JRadioButton();
        good_m1 = new javax.swing.JRadioButton();
        damage_m1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        discription1 = new javax.swing.JTextArea();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Renting Machines");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Machine Brand");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Type");

        macine_type.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        macine_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Color", "Black" }));

        brand_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        brand_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Ricoh", "Toshiba", " " }));

        count_copy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        count_copy.setToolTipText("Customer Name");

        copy_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        copy_txt.setText("Copy Count");

        serial_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        serial_txt.setText("Machine Serial");

        m_serial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        m_serial.setToolTipText("Customer Name");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Machine Status");

        new_m.setBackground(new java.awt.Color(255, 255, 255));
        new_m.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        new_m.setText("Brand New");

        good_m.setBackground(new java.awt.Color(255, 255, 255));
        good_m.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        good_m.setText("Good Conditions");

        damage_m.setBackground(new java.awt.Color(255, 255, 255));
        damage_m.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        damage_m.setText("External Damaged");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Discription");

        discription.setColumns(20);
        discription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        discription.setRows(5);
        discription.setToolTipText("Address");
        jScrollPane2.setViewportView(discription);

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Plus_35px.png"))); // NOI18N
        add.setText("Add Record");
        add.setIconTextGap(10);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Add_New_40px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(count_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_serial, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(copy_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brand_name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(macine_type, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(new_m)
                                .addGap(18, 18, 18)
                                .addComponent(good_m)
                                .addGap(18, 18, 18)
                                .addComponent(damage_m))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macine_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(copy_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(count_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(serial_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_serial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_m)
                    .addComponent(good_m)
                    .addComponent(damage_m))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Machine", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Machine Brand");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Type");

        macine_type1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        macine_type1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Color", "Black" }));

        brand_name1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        brand_name1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Ricoh", "Thoshiba", " " }));

        count_copy1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        count_copy1.setToolTipText("Customer Name");

        copy_txt1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        copy_txt1.setText("Copy Count");

        serial_txt1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        serial_txt1.setText("Machine Serial");

        m_serial1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        m_serial1.setToolTipText("Customer Name");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Machine Status");

        new_m1.setBackground(new java.awt.Color(255, 255, 255));
        new_m1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        new_m1.setText("Brand New");

        good_m1.setBackground(new java.awt.Color(255, 255, 255));
        good_m1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        good_m1.setText("Good Conditions");

        damage_m1.setBackground(new java.awt.Color(255, 255, 255));
        damage_m1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        damage_m1.setText("External Damaged");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Discription");

        discription1.setColumns(20);
        discription1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        discription1.setRows(5);
        discription1.setToolTipText("Address");
        jScrollPane3.setViewportView(discription1);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Delete_35px.png"))); // NOI18N
        delete.setText("Delete Record");
        delete.setIconTextGap(10);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Restart_35px.png"))); // NOI18N
        update.setText("Update Record");
        update.setIconTextGap(10);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(count_copy1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serial_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_serial1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(copy_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brand_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(macine_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(new_m1)
                                .addGap(18, 18, 18)
                                .addComponent(good_m1)
                                .addGap(18, 18, 18)
                                .addComponent(damage_m1))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macine_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(copy_txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(count_copy1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(serial_txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_serial1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel13)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_m1)
                    .addComponent(good_m1)
                    .addComponent(damage_m1))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 27, Short.MAX_VALUE)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane2.addTab("Edit ", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        String brand = brand_name.getSelectedItem().toString();
        String type = macine_type.getSelectedItem().toString();
        String serial = m_serial.getText();
        String copyc = count_copy.getText();
        boolean newM = new_m.isSelected();
        boolean goodM = good_m.isSelected();
        boolean damageM = damage_m.isSelected();
        String disc = discription.getText();
        
        String machineStatus = "";
        
        if(newM == true){
            
            machineStatus = "Brand New";
        }
        else if(goodM == true){
            
            machineStatus = "Good Condition";
        }
        else if(damageM == true){
            
            machineStatus = "External Damages";
        }
        else if(validateNumbers(serial) == false || validateSerialNumber(serial) == false){
            
            JOptionPane.showMessageDialog(null, "Serial number should contain 10 numbers, Can not contain letters or characters");
            serial_txt.setForeground(Color.RED);
        }
        else if(validateNumbers(copyc)== false){
            
            JOptionPane.showMessageDialog(null, "Copy Count should contain numbers, Can not contain letters or characters");
            copy_txt.setForeground(Color.RED);
        }   
          
        String addQuery = "INSERT INTO available_machines VALUES(?, ?, ?, ?, ?, ?)";
        
        PreparedStatement ps;
        
        try {
            
            ps = getConnection().prepareStatement(addQuery);
            
            ps.setString(1, serial);
            ps.setString(2, brand);
            ps.setString(3, type);
            ps.setString(4, copyc);
            ps.setString(5, machineStatus);
            ps.setString(6, disc);
            
            ps.executeUpdate();
        
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
        
        JOptionPane.showMessageDialog(null, "Data Added Sucessfuly", "Informer", 1);
        close();
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       
        String serial = m_serial1.getText();
        
        String query = "DELETE FROM available_machines WHERE machineSerial = '"+serial+"'";
        
        try {
            
            PreparedStatement ps = getConnection().prepareStatement(query);
            ps.executeUpdate();
            
        } catch (Exception e) {
            
             JOptionPane.showMessageDialog(null, e);
        }
         
        JOptionPane.showMessageDialog(null, "Record Removed", "Informer", 1);
        close();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       
        String brand = brand_name1.getSelectedItem().toString();
        String type = macine_type1.getSelectedItem().toString();
        String serial = m_serial1.getText();
        String copyc = count_copy1.getText();
        boolean newM = new_m1.isSelected();
        boolean goodM = good_m1.isSelected();
        boolean damageM = damage_m1.isSelected();
        String disc = discription1.getText();
        
        String machineStatus = "";
        
        if(newM == true){
            
            machineStatus = "Brand New";
        }
        else if(goodM == true){
            
            machineStatus = "Good Condition";
        }
        else if(damageM == true){
            
            machineStatus = "External Damages";
        }
        
         
            String query = "UPDATE available_machines "
                    + "SET brand = '"+brand+"', type = '"+type+"', copycount = '"+copyc+"', status = '"+machineStatus+"', discrip = '"+disc+"'"
                    + "WHERE machineSerial = '"+serial+"'";
        
        try {
            
            PreparedStatement ps = getConnection().prepareStatement(query);
            
            ps.executeUpdate();
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
          
        JOptionPane.showMessageDialog(null, "Data Updated Sucessfuly", "Informer", 1);
        close();
    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        discription.setText("Brand New Machine");
        count_copy.setText("0");
        m_serial.setText("8911109219");
        new_m.setSelected(true);
        brand_name.setSelectedItem("Ricoh");
        macine_type.setSelectedItem("Color");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Machine_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Machine_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Machine_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Machine_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Machine_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> brand_name;
    private javax.swing.JComboBox<String> brand_name1;
    private javax.swing.JLabel copy_txt;
    private javax.swing.JLabel copy_txt1;
    private javax.swing.JTextField count_copy;
    private javax.swing.JTextField count_copy1;
    private javax.swing.JRadioButton damage_m;
    private javax.swing.JRadioButton damage_m1;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea discription;
    private javax.swing.JTextArea discription1;
    private javax.swing.JRadioButton good_m;
    private javax.swing.JRadioButton good_m1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField m_serial;
    private javax.swing.JTextField m_serial1;
    private javax.swing.JComboBox<String> macine_type;
    private javax.swing.JComboBox<String> macine_type1;
    private javax.swing.JRadioButton new_m;
    private javax.swing.JRadioButton new_m1;
    private javax.swing.JLabel serial_txt;
    private javax.swing.JLabel serial_txt1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
