/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package office_man_system;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pasindu Senarathne
 */
public class Update_Machine extends javax.swing.JFrame {

    /**
     * Creates new form Update_Machine
     */
    public Update_Machine() {
        initComponents();
    }
    
    public Update_Machine(String nic,String brand,String type,String copyCount,String serial,String machineStatus, String dis ) {
        
        initComponents();
   
        if(brand.equals("Toshiba")){
            
            brand_name.setSelectedItem(brand);
        }
        if(brand.equals("Ricoh")){
            
            brand_name.setSelectedItem(brand);
        }
        
        if(type.equals("Color")){
            
            macine_type.setSelectedItem("Color");
        }
        if(type.equals("Black")){
            
            macine_type.setSelectedItem("Black");
        }
        
        count_copy.setText(copyCount);
        m_serial.setText(serial);
        
        if(machineStatus.equals("Brand New")){
            
            new_m.setSelected(true);
        }
        if(machineStatus.equals("Good Condition")){
            
            good_m.setSelected(true);
        }
        if(machineStatus.equals("External Damages")){
            
            damage_m.setSelected(true);
        }
        discription.setText(dis);
        nicTxt.setText(nic);
        
        
    }
     public Connection getConnection(){
        
        Connection con;
        try {
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/office_management_system?autoReconnect=true&useSSL=false","root","root");
            return con;
            
        } catch (Exception e) {
            
            e.printStackTrace();
            return null;
        }
      
    }
    
    public void close(){
        
        WindowEvent windowClose;
        windowClose = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowClose);
    }
    
     public boolean validateLetter(String string){
	        
	        int val;
	        boolean ret = true;
	        
	        for(int i = 0; i < string.length(); i++){
	            
	            val = (int)string.charAt(i);
	            
	            if(!(((val >=65) && (val <= 90)) || ((val >= 97) && (val <= 122)) || val == 32)){
	                
	                ret = false;
	            }
	            
	        }
	        
	        return ret;
    }
    
   
    
    public boolean validateSerialNumber(String string){
        
        if(string.length() == 10){
            
            return true;
        }
        else{
            
            return false;
        }
    }
    
    public boolean validateNumbers(String string){
	        
	        int val;
	        boolean ret = true;
	        
	        for(int i = 0; i < string.length(); i++){
	            
	            val = (int)string.charAt(i);
	            
	            if(!((val <= 57) && (val >= 48 ))){
	                
	                ret = false;
	            }
	            
	        }
	        
	        return ret;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        macine_type = new javax.swing.JComboBox<>();
        brand_name = new javax.swing.JComboBox<>();
        copy_txt = new javax.swing.JLabel();
        count_copy = new javax.swing.JTextField();
        serial_txt = new javax.swing.JLabel();
        m_serial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        new_m = new javax.swing.JRadioButton();
        good_m = new javax.swing.JRadioButton();
        damage_m = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        discription = new javax.swing.JTextArea();
        update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nicTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Machine Record");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Machine Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Machine Brand");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Type");

        macine_type.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        macine_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Color", "Black" }));

        brand_name.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        brand_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Ricoh", "Toshiba", " " }));

        copy_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        copy_txt.setText("Copy Count");

        count_copy.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        count_copy.setToolTipText("Customer Name");

        serial_txt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        serial_txt.setText("Machine Serial");

        m_serial.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        m_serial.setToolTipText("Customer Name");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Machine Status");

        new_m.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(new_m);
        new_m.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        new_m.setText("Brand New");

        good_m.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(good_m);
        good_m.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        good_m.setText("Good Conditions");

        damage_m.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(damage_m);
        damage_m.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        damage_m.setText("External Damaged");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Discription");

        discription.setColumns(20);
        discription.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        discription.setRows(5);
        discription.setToolTipText("Address");
        jScrollPane2.setViewportView(discription);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/office_man_system/images/icons8_Restart_35px.png"))); // NOI18N
        update.setText("Update Record");
        update.setIconTextGap(10);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Customer NIC");

        nicTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nicTxt.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nicTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(count_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_serial, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copy_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brand_name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(macine_type, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(new_m)
                        .addGap(18, 18, 18)
                        .addComponent(good_m)
                        .addGap(18, 18, 18)
                        .addComponent(damage_m))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macine_type, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(copy_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(count_copy, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(serial_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_serial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_m)
                    .addComponent(good_m)
                    .addComponent(damage_m))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        String brand = brand_name.getSelectedItem().toString();
        String type = macine_type.getSelectedItem().toString();
        String copyCount = count_copy.getText();
        String serial = m_serial.getText();
        String dis = discription.getText();
        String nicN = nicTxt.getText();
        
        boolean newM = new_m.isSelected();
        boolean goodM = good_m.isSelected();
        boolean damageM = damage_m.isSelected();
        
        String machineStatus = "";
        
        if(newM == true){
            
            machineStatus = "Brand New";
        }
        else if(goodM == true){
            
            machineStatus = "Good Condition";
        }
        else if(damageM == true){
            
            machineStatus = "External Damages";
        }
         else if(validateNumbers(serial) == false || validateSerialNumber(serial) == false){
            
            JOptionPane.showMessageDialog(null, "Serial number should contain 10 numbers, Can not contain letters or characters");
            serial_txt.setForeground(Color.RED);
        }
        else if(validateNumbers(copyCount)== false){
            
            JOptionPane.showMessageDialog(null, "Copy Count should contain numbers, Can not contain letters or characters");
            copy_txt.setForeground(Color.RED);
        }   
          
        String queryUpdate = "UPDATE rented_machine_records "
                    + "SET machineBrand = '"+brand+"' , machineType = '"+type+"', serialNum = '"+serial+"', copyCount = '"+copyCount+"', status = '"+machineStatus+"', discription = '"+dis+"'"
                    + "WHERE nic = '"+nicN+"'";
        
        try {
            PreparedStatement ps = getConnection().prepareStatement(queryUpdate);
             ps.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(Update_Machine.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Record Updated Sucessfully", "Informer", 1);
        close();
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Machine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brand_name;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel copy_txt;
    private javax.swing.JTextField count_copy;
    private javax.swing.JRadioButton damage_m;
    private javax.swing.JTextArea discription;
    private javax.swing.JRadioButton good_m;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField m_serial;
    private javax.swing.JComboBox<String> macine_type;
    private javax.swing.JRadioButton new_m;
    private javax.swing.JLabel nicTxt;
    private javax.swing.JLabel serial_txt;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
